# Generated by Django 3.1.2 on 2020-10-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=104)),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
    ]
