# Generated by Django 3.1.2 on 2020-10-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=104)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
    ]
