# Generated by Django 3.1.2 on 2020-10-06 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(db_column='id_department', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.department'),
        ),
    ]
