# Generated by Django 3.1.2 on 2020-10-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='comission_percentage',
            field=models.DecimalField(db_column='comission_percentage', decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
