# Generated by Django 3.1.2 on 2020-10-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(through='core.ProductCategory', to='core.Product'),
        ),
    ]
