# Generated by Django 3.1.2 on 2020-10-07 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201007_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelBase',
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(db_column='active', default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='modifed_at',
            field=models.DateTimeField(auto_now=True, db_column='modified_at'),
        ),
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(db_column='active', default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='modifed_at',
            field=models.DateTimeField(auto_now=True, db_column='modified_at'),
        ),
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(db_column='active', default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='modifed_at',
            field=models.DateTimeField(auto_now=True, db_column='modified_at'),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_column='active', default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='modifed_at',
            field=models.DateTimeField(auto_now=True, db_column='modified_at'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='active',
            field=models.BooleanField(db_column='active', default=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='modifed_at',
            field=models.DateTimeField(auto_now=True, db_column='modified_at'),
        ),
    ]
