# Generated by Django 3.1.2 on 2020-10-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201007_0048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('category', 'product')},
        ),
    ]
