# Generated by Django 3.1.2 on 2020-10-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201007_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='modifed_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='modifed_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='modifed_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='modifed_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='modifed_at',
            new_name='modified_at',
        ),
    ]
